zdanie = input("Podaj zdanie: ")
wyrazy = zdanie.split()
zdanie_sformatowane = ' '.join(word.capitalize() for word in wyrazy)
print("Zdanie z każdym wyrazem zaczynającym się i kończącym wielką literą:")
print(zdanie_sformatowane)
